#apiVersion: v1
#kind: ReplicationController
#metadata:
#  name: bl-mem-store-master
#  labels:
#    name: bl-mem-store-master
#spec:
#  replicas: 1
#  template:
#    metadata:
#      labels:
#        name: bl-mem-store-master
#    spec:
#      containers:
#      - name: master
#        image: redis
#        ports:
#        - containerPort: 6379
#
#---
apiVersion: v1
kind: Service
metadata:
  name: bl-mem-store-master
  namespace: index
  labels:
    app: redis
    role: master
    tier: backend
spec:
  type: LoadBalancer
  ports:
    - port: 6379
  selector:
    app: redis
    role: master
    tier: backend