apiVersion: extensions/v1beta1
  kind: Deployment
metadata:
  name: redis-slave
  spec:
    replicas: 2
  template:
  metadata:
    labels:
      app: redis
      role: slave
      tier: backend
    spec:
      containers:
      - name: slave
        image: gcr.io/google_samples/gb-redisslave:v1
        ports:
        - containerPort: 6379